#!/usr/bin/python3

"""
This Python script takes in a letter and sends a POST request to
http://0.0.0.0:5000/search_user with the letter as a parameter.

The letter must be sent in the variable q
If no argument is given, set q=""
If the response body is properly JSON formatted and not empty,
display the id and name like this: [<id>] <name>
Otherwise:
Display Not a valid JSON if the JSON is invalid
Display No result if the JSON is empty

You must use the package requests and sys
You are not allowed to import packages other than requests and sys
Please test your script in the sandbox provided, using the
web server running on port 5000. All JSON generated by this server are random.

Usage: ./8-json_api.py <letter>
"""


import requests
import sys


def search_user(q):
    url = 'http://0.0.0.0:5000/search_user'
    data = {'q': q}

    response = requests.post(url, data=data)

    if response.status_code == 200:
        try:
            data = response.json()
            if data:
                print('[{}] {}'.format(data['id'], data['name']))
            else:
                print('No result')
        except ValueError:
            print('Not a valid JSON')
    else:
        print('No result')


if __name__ == "__main__":
    q = sys.argv[1] if len(sys.argv) > 1 else ''
    search_user(q)
